include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm9605a_ykl_LP047HPTP042A_HSD_dsi_2_qhd")
obj-y   +=  otm9605a_ykl_LP047HPTP042A_HSD_dsi_2_qhd.o
endif
